# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe5b4b6fc8c6f58745ea6756e63c7696e81f45b82df9562df5a1a084553f3235ed903fc83809f193206079ff4db5fcee16a27d305b613b53d9d11e09e2988a74

test:
  secret_key_base: 0e7eed9beb45a723e67bd1b696958843799b7af8066e64d8005170bb9f72a9372dc4b58ee2cd8d0bfe96a69f983bf8a4197845f8f2163c50eb4719a09decb0c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
